apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: hydrator-2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hydrator-demo
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: hydrator-demo-0.1.0
  name: hydrator-2-hydrator-demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: hydrator-2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hydrator-demo
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: hydrator-demo-0.1.0
  name: hydrator-2-hydrator-demo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: hydrator-2
    app.kubernetes.io/name: hydrator-demo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: hydrator-2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hydrator-demo
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: hydrator-demo-0.1.0
  name: hydrator-2-hydrator-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: hydrator-2
      app.kubernetes.io/name: hydrator-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hydrator-2
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: hydrator-demo
        app.kubernetes.io/version: 1.16.0
        helm.sh/chart: hydrator-demo-0.1.0
    spec:
      containers:
        - image: nginx:1.16.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: hydrator-demo
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
          securityContext: {}
      securityContext: {}
      serviceAccountName: hydrator-2-hydrator-demo
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/instance: hydrator-2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hydrator-demo
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: hydrator-demo-0.1.0
  name: hydrator-2-hydrator-demo-test-connection
spec:
  containers:
    - args:
        - hydrator-2-hydrator-demo:80
      command:
        - wget
      image: busybox
      name: wget
  restartPolicy: Never
