apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: release-name
  name: release-name-helm-guestbook
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: helm-guestbook
    release: release-name
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: release-name
  name: release-name-helm-guestbook
spec:
  progressDeadlineSeconds: 5
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-guestbook
      release: release-name
  template:
    metadata:
      labels:
        app: helm-guestbook
        release: release-name
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: helm-guestbook
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          limits:
            cpu: 2000m

---

