apiVersion: stable.example.com/v1
kind: CronTab
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: test:stable.example.com/CronTab:/my-new-cron-object
  name: my-new-cron-object
spec:
  cronSpec: null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: test:apps/Deployment:/guestbook-ui
  name: guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: guestbook-ui
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: test:/Service:/guestbook-ui
  name: guestbook-ui
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: guestbook-ui
---
apiVersion: v1
data:
  config.yaml: |
    a: bah
    b: cba
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: test:/ConfigMap:/test-cm
  name: test-cm
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: test:/Secret:/nats-box-contexts
    vault.security.banzaicloud.io/inline-mutation: "true"
    vault.security.banzaicloud.io/vault-role: nats
    vault.security.banzaicloud.io/vault-skip-verify: "true"
  labels:
    app.kubernetes.io/instance: redacted-nats
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.10.1
  name: nats-box-contexts
stringData:
  default.json: |
    {
      "url": "nats://redacted-nats:4222",
      "user": "natsbox",
      "password": "${vault:/secret/data/redacted/nats/natsusers#NATSBOXPW}"
    }
type: Opaque
