namePrefix: pre-post-sync-

bases:
- ../kustomize-guestbook

resources:
- post-sync-job.yaml

images:
  - name: gcr.io/heptio-images/ks-guestbook-demo
    newName: gcr.io/heptio-images/ks-guestbook-demo
    newTag: "0.1"
