namePrefix: pre-post-sync-

bases:
- ../kustomize-guestbook

resources:
- post-sync-job.yaml

images:
  - name: quay.io/crenshaw_dev/guestbook-demo
    newName: quay.io/crenshaw_dev/guestbook-demo
    newTag: "0.2"
