apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  labels:
    argocd.argoproj.io/instance: csi-driver-nfs
  name: nfs.csi.k8s.io
spec:
  attachRequired: false
  fsGroupPolicy: File
  volumeLifecycleModes:
    - Persistent
