apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: prod-west
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: big-helm
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: big-helm-0.1.0
  name: prod-west-big-helm

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: prod-west
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: big-helm
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: big-helm-0.1.0
  name: prod-west-big-helm
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: prod-west
    app.kubernetes.io/name: big-helm
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: prod-west
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: big-helm
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: big-helm-0.1.0
  name: prod-west-big-helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: prod-west
      app.kubernetes.io/name: big-helm
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: prod-west
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: big-helm
        app.kubernetes.io/version: 1.16.0
        helm.sh/chart: big-helm-0.1.0
    spec:
      containers:
        - image: nginx:1.16.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: big-helm
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
          securityContext: {}
      securityContext: {}
      serviceAccountName: prod-west-big-helm

---

apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/instance: prod-west
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: big-helm
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: big-helm-0.1.0
  name: prod-west-big-helm-test-connection
spec:
  containers:
    - args:
        - prod-west-big-helm:80
      command:
        - wget
      image: busybox
      name: wget
  restartPolicy: Never

---

