apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - test: test
  goTemplate: true
  template:
    metadata:
      name: 'test'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: 'default'
      sources:
      - repoURL: https://github.com/crenshaw-dev/argocd-example-apps.git
        targetRevision: master
        path: 20331/vpa
        helm:
          valuesObject:
            vpa:
              enabled: '{{ default true .vpa.enabled }}'
              updateMode: '{{ default "Off" .vpa.updateMode }}'
              minAllowed:
                memory: '{{ default "64Mi" .vpa.minAllowed.memory }}'
              maxAllowed:
                memory: '{{ default "2Gi" .vpa.maxAllowed.memory }}'