apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: app
  labels:
    app.kubernetes.io/instance: app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: app
    app.kubernetes.io/version: 2.0.0
    helm.sh/chart: app-2.0.0
  name: app
spec:
  ports:
    - name: http
      nodePort: 30171
      port: 80
      protocol: TCP
      targetPort: http
    - name: prometheus-http
      nodePort: 32577
      port: 2112
      protocol: TCP
      targetPort: prometheus-http
  selector:
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: app
  sessionAffinity: None
  type: NodePort