apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-guestbook
    app.kubernetes.io/instance: test-east
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: test-east
  name: test-east-helm-guestbook
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: helm-guestbook
    release: test-east
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-guestbook
    app.kubernetes.io/instance: test-east
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: test-east
  name: test-east-helm-guestbook
spec:
  progressDeadlineSeconds: 5
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-guestbook
      release: test-east
  template:
    metadata:
      labels:
        app: helm-guestbook
        release: test-east
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: helm-guestbook
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          limits:
            cpu: 2000m

---

