apiVersion: external-secrets.io/v1
kind: ExternalSecret
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mykey
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-secretsmanager-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: intranet-plataforma